services:
  mongo:
    image: mongo:8
    command: mongod --quiet --logpath /dev/null
    volumes:
      - data:/data/db
    ports:
      - "27017:27017"

  lachsbot:
    depends_on: [ "mongo" ]
    build: .
    volumes:
      - ./config:/opt/lachsbot-app/config
    environment:
      #TOKEN: "CHANGE ME"
      DB_NAME: "lachsbot"
      DB_CONNECTION_STR: "mongodb://mongo:27017"

volumes:
  data:

